title = "ai-life-coach gitleaks"

[allowlist]
description = "Allow Firebase web api key; ignore local venv"
# Firebase Web API keys are public by design in frontend apps.
regexes = [
  '''AIza[0-9A-Za-z\-_]{35}'''
]
paths = [
  '''^\.venv/'''   # your virtualenv should be gitignored anyway
]
